Repository Nintails-TF/ncr-agile-wombo, pull requests merged in 2024-01, with the labels that each got.

#23 Created Isssue template
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: documentation

#19 Create CONTRIBUTING.md
  CONTRIBUTING.md
  pull-request-template.md
Labels: documentation

#42 Update pull-request-template.md
  pull-request-template.md
Labels: documentation

#39 Added basic express API server
  api/.gitignore
  api/package-lock.json
  api/package.json
  api/server.js
Labels: enhancement

#61 feat: initialised the node server working with the database
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/server.js
Labels: enhancement

#65 Added mongoDB to server
  api/package-lock.json
  api/package.json
  api/server.js
Labels: enhancement

#66 Be/server.js fix
  api/api_server.js
  api/server.js
  be/backend_server.js
  be/package-lock.json
Labels: bug

#69 API/express server improvements
  .gitignore
  api/api_server.js
  api/server.js
  be/package-lock.json
  be/server.js
Labels: enhancement

#70 Renamed the api server again
  api/api_server.js
Labels: bug

#73 Removed unused mongo package and connected with mongoose.
  api/api_server.js
Labels: enhancement

#74 Get User's Geolocation
  fe/dist/style.css
  fe/map.html
  fe/src/input.css
Labels: enhancement

#79 Update README.md
  README.md
Labels: documentation

#81 Got queries working
  api/api_server.js
Labels: API

#82 Querying ATMs/Branches by ID
  api/api_server.js
Labels: API

#83 API/atms-routes
  .gitignore
  .vs/slnx.sqlite
  api/api_server.js
Labels: enhancement, API

#89 Added Accessibility, ContactInfo, Services and PostalAddress endpoints
  api/api_server.js
Labels: API

#90 Endpoints for all branch properties
  api/api_server.js
Labels: API

#93 Hosted the API server on Google App Engine
  api/.gcloudignore
  api/api_server.js
  api/app.yaml
  api/package.json
  api/schemas.js
Labels: API

#94 Designed dropdown box for filters
  fe/dist/style.css
  fe/map.html
  fe/src/input.css
Labels: enhancement, Front-end

#95 API/more-atm-routes
  .gitignore
  .vs/VSWorkspaceState.json
  .vs/ncr-agile-wombo/v17/.wsuo
  api/api_server.js
Labels: enhancement, API

#98 HTML Validation Fixes
  fe/map.html
Labels: bug

#102 feat(backend) api fetch function
  be/package-lock.json
  be/package.json
  be/server.js
Labels: Back-end

#106 Added branches crud
  api/api_server.js
Labels: API

#103 Create ci.yml
  .github/ci.yml
Labels: DevOps

#105 Circle Search Radius
  fe/map.html
Labels: enhancement, Front-end

#108 Be/adding jest
  .eslintrc.json
  be/__tests__/server.test.js
  be/package-lock.json
  be/package.json
  be/server.js
Labels: Back-end

#111 feat(backend): backend gets branches and atms in a list
  be/server.js
Labels: Back-end

#114 Be/get all location coordinates
  be/server.js
Labels: enhancement, Back-end

#118 feat(docs): Added the API docs
  api/api_docs.json
Labels: enhancement, API

#115 Created a List View for ATMs and Branches
  fe/dist/style.css
  fe/images/wifi.png
  fe/map.html
  fe/src/input.css
Labels: enhancement, Front-end

#120 Removed bracket
  fe/map.html
Labels: bug, Front-end

#122 Radius
  fe/map.html
Labels: enhancement, Front-end

#121 feat(list-view_information): backend now returns a more useful list or the list view to use
  be/server.js
Labels: enhancement, Back-end

#125 feat(list-view): added more fields to the data
  be/server.js
Labels: enhancement, Back-end

#124 fix: API/refining-API-Server
  api/.env
  api/api_server.js
  api/atmRoutes.js
  api/branchRoutes.js
  api/package-lock.json
  api/package.json
Labels: enhancement, API

#131 feat:implemented stuff
  be/server.js
  fe/map.html
Labels: enhancement, Back-end

#132 Update ci.yml
  .github/ci.yml
Labels: DevOps

#133 API/further-API-improvements
  api/api_server.js
  api/atmRoutes.js
  api/branchRoutes.js
  api/database.js
  package-lock.json
Labels: enhancement, API

#135 Show Branch Markers on the Map
  fe/map.html
Labels: enhancement, Front-end

#138 Show ATMs on Map and Attached Simple Popups to Branches/ATM Markers
  be/server.js
  fe/map.html
Labels: enhancement, Front-end

#136 Update README.md with SCRUM meeting Youtube link
  README.md
Labels: documentation

#155 API/API-improvements
  api/api_server.js
  api/database.js
  api/package-lock.json
  api/package.json
Labels: enhancement, API

#156 Endpoints with filtering
  api/api_docs.json
  api/api_server.js
  api/atmRoutes.js
  api/branchRoutes.js
  api/package-lock.json
  api/package.json
Labels: enhancement, API

#159 Added branch/atm data into the list view
  fe/dist/style.css
  fe/map.html
Labels: enhancement, Front-end

#164 feat(API): Hosted the API docs on the same server
  api/api_server.js
  api/package-lock.json
  api/package.json
  api/swagger.json
Labels: API

#172 Fe/issue144/map buttons
  fe/map.html
Labels: enhancement, Front-end

#166 Api/endpoints with location radius filtering
  api/atmRoutes.js
  api/branchRoutes.js
  api/swagger.json
Labels: API

#176 BE/fix-for-outofdate-branch
  be/routes.js
  be/server.js
Labels: Back-end

#182 BE/filter-fixes
  be/database.js
  be/package-lock.json
  be/package.json
  be/routes.js
  be/server.js
  be/utils.js
Labels: Back-end
