Repository Nintails-TF/ncr-agile-wombo, pull requests merged in 2024-02, with the labels that each got.

#190 Fixing the templates issue
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/pull-request-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
Labels: bug, documentation

#191 Rename PR-issue-checker.yaml to PR-issue-checker.yaml
  .github/ARCHIVE/PR-issue-checker.yaml
Labels: DevOps

#194 List view opens marker on click
  fe/dist/style.css
  fe/map.html
  fe/src/input.css
Labels: enhancement, Front-end

#189 BE/caching
  be/cacheUtil.js
  be/package-lock.json
  be/package.json
  be/routes.js
  be/utils.js
Labels: enhancement, Back-end

#196 FE/fixing-google-maps-button
  fe/map.html
Labels: enhancement, Front-end

#198 Api/fixing the filters
  .gcloudignore
  .gitignore
  api/atmRoutes.js
  api/branchRoutes.js
  backend.yaml
  be/server.js
  package-lock.json
  package.json
Labels: API

#197 feat(be): Hosting the backend and frontend on GAE
  .gcloudignore
  .gitignore
  backend.yaml
  be/server.js
  package-lock.json
  package.json
Labels: Back-end

#199 FE/script-move
  fe/js/mapScript.js
  fe/map.html
Labels: Front-end

#201 Filters added
  be/routes.js
  fe/dist/style.css
  fe/js/mapScript.js
  fe/map.html
Labels: enhancement, Front-end

#203 Update workflows.yaml
  .github/workflows/workflows.yaml
Labels: API, DevOps

#205 BE/fix
  be/routes.js
  fe/dist/style.css
  fe/js/mapScript.js
  fe/map.html
Labels: Back-end

#207 fix(API): lint fix
  api/api_server.js
  api/atmRoutes.js
  api/package.json
  fe/node_modules/.package-lock.json
  fe/package-lock.json
  fe/package.json
Labels: API

#208 Be/adding hooks
  .husky/commit-msg
  .husky/pre-push
  be/package-lock.json
  be/package.json
  commitlint.config.js
  package-lock.json
  package.json
Labels: DevOps

#210 Update README.md
  README.md
Labels: documentation

#211 Update README.md
  README.md
Labels: documentation
